### ISSUE TITLE
Status of this repo?

### ISSUE THREAD

**Issue by pelson** [nansencenter/conda-recipes#3]
Hi @aleksandervines & @akorosov.

First and foremost, thanks for making this repo exist! I'm a huge believer in making conda recipes easily sharable.

I know you have both contributed to conda-forge in the past, so I thought I'd reach out and find out whether you might be interested in cross-referencing the conda-forge recipe equivalents in some way?

Not to worry if not - I won't be offended, 😄 , I just thought I'd ask the question - hope you don't mind.

Best,

Phil

**Comment by aleksandervines** [comment]
Hi @pelson ,

I'd say the current status of this repo is that it is not currently maintained. We've contributed to conda-forge and added our requirements to the required repositories in order to not have to maintain this repo by ourselves. Now we try to help maintain conda-forge in order for it to continue supporting our requirements.

Aleksander
